#! /bin/sh

####################################################
#                                                   #
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗    #
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║    #
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║    #
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║    #
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║    #
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝    # 
#####################################################


pgrep -x sxhkd > /dev/null || 
sxhkd &
nitrogen --restore &
picom -f &
~/.config/polybar/launch.sh &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

########## Window Settings ##############
bspc config border_width         0
bspc config window_gap           10
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true

########## Border Colors #################
bspc config focused_border_color "#2E3440"
bspc config normal_border_color "#2E3440"

######### Program settings ################
bspc rule -a Gimp desktop='^8' state=floating follow=on


######### Other Settings ################
xsetroot -cursor_name left_ptr &
xbacklight -set 30

