; MODULES ARE STOLEN FROM ARCHCRAFT and is Created By Aditya Shakya @adi1090x

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.background}
format-volume-padding = 2

format-muted = <label-muted>
format-muted-prefix = 婢
format-muted-background = ${color.background}
format-muted-padding = 2

label-volume = %percentage%%

label-muted = " "
label-muted-foreground = ${color.foreground}

ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 墳

ramp-headphones-0 = 

wm-restack = bspwm

cursor-click = pointer

[module/alsa]
type = internal/alsa

master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master
interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.background}
format-volume-padding = 2

format-muted = <label-muted>
format-muted-prefix = 婢
format-muted-background = ${color.background}
format-muted-padding = 2

label-volume = %percentage%%

label-muted = " "
label-muted-foreground = ${color.foreground}

ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 墳

ramp-headphones-0 = 



[module/battery]
type = internal/battery

full-at = 100

battery = BAT1
adapter = ACAD

poll-interval = 2

time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.background}
format-charging-padding = 2

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.background}
format-discharging-padding = 2

format-full = <label-full>
format-full-prefix = 
format-full-background = ${color.background}
format-full-padding = 2

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = " Full"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 

animation-charging-framerate = 750



[module/cpu]
type = internal/cpu
interval = 1

format = <label>
format-prefix = ﬙
format-background = ${color.background}
format-padding = 2

label = " %percentage%%"



[module/date]
type = internal/date

interval = 1.0
time = " %I:%M %p"
time-alt = " %a, %d %b %Y"

format = <label>
format-background = ${color.background}
format-padding = 2

label = %time%



[module/filesystem]
type = internal/fs

mount-0 = /
interval = 30
fixed-values = true

format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-background = ${color.background}
format-mounted-padding = 2

format-unmounted = <label-unmounted>
format-unmounted-prefix = 
format-unmounted-background = ${color.background}
format-unmounted-padding = 2

label-mounted = " %free%"
label-unmounted = " %mountpoint%: not mounted"




[module/memory]
type = internal/memory

interval = 1

format = <label>
format-prefix = 
format-background = ${color.background}
format-padding = 2

label = " %mb_used%"



[module/wired-network]
type = internal/network
interface = eth0

[module/wireless-network]
type = internal/network
interface = wlan0

; Normal Module
[module/network]
type = internal/network
interface = wlan0

interval = 1.0

accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal>
format-connected-background = ${color.background}
format-connected-padding = 2

format-disconnected = <label-disconnected>
format-disconnected-prefix = 睊
format-disconnected-background = ${color.background}
format-disconnected-padding = 2

label-connected = "%{A1:networkmanager_dmenu &:}connected%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:}%{A}"

ramp-signal-0 = 直
ramp-signal-1 = 直
ramp-signal-2 = 直



[module/title]
type = internal/xwindow

format = <label>
format-prefix = ﯑
format-background = ${color.background}
format-padding = 2

label = " %title%"
label-maxlen = 30



[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 

format = <label-state>
format-padding = 1
format-background = ${color.background}

label-monitor = %name%
label-active = 
label-active-foreground = ${color.foreground}
label-occupied = 
label-occupied-foreground = ${color.foreground}
label-urgent = 
label-urgent-foreground = ${color.background}

label-empty = 

label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1



[module/launcher]
type = custom/text
content = 
enable-click = true
content-background = ${color.background}
content-foreground = ${color.foreground}
content-padding = 3

click-left = ~/off.sh &



[module/sysmenu]
type = custom/text
content = 襤
enable-click = true

content-background = ${color.background}
content-foreground = ${color.foreground}
content-padding = 2



click-left = /home/aoki/.config/bspwm/rofi/bin/powermenu &
